---
name: hw2
class_id: "BerkeleyX/CS169.1xb/Software_as_a_Service_part_1_rev_Fall_2013_"
due_date: 2013-10-07 06:59:00+00:00
late_penalty: 0.25
modules:
  - id: "i4x://BerkeleyX/CS169.1xb/problem/0df0112801384fa093d6928e6eb6eacc"
    points: 100
